version: '3.0'
services:

  app:
    build: ./app
    container_name: app
    ports:
      - 8000:8000
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  pg_data: