version: '3.1'
services:
  db:
    image: postgres:14.3-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
